version: '3.8'
services:
  backend:
    build: ./crm-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/crm
  frontend:
    build: ./crm-frontend
    ports:
      - "3000:3000"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
